
package com.pos.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ManterReservaService", targetNamespace = "http://services.pos.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ManterReservaService {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "onConstruct", targetNamespace = "http://services.pos.com/", className = "com.pos.services.OnConstruct")
    @ResponseWrapper(localName = "onConstructResponse", targetNamespace = "http://services.pos.com/", className = "com.pos.services.OnConstructResponse")
    @Action(input = "http://services.pos.com/ManterReservaService/onConstructRequest", output = "http://services.pos.com/ManterReservaService/onConstructResponse")
    public void onConstruct();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "onDestroy", targetNamespace = "http://services.pos.com/", className = "com.pos.services.OnDestroy")
    @ResponseWrapper(localName = "onDestroyResponse", targetNamespace = "http://services.pos.com/", className = "com.pos.services.OnDestroyResponse")
    @Action(input = "http://services.pos.com/ManterReservaService/onDestroyRequest", output = "http://services.pos.com/ManterReservaService/onDestroyResponse")
    public void onDestroy();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "excluirReserva", targetNamespace = "http://services.pos.com/", className = "com.pos.services.ExcluirReserva")
    @ResponseWrapper(localName = "excluirReservaResponse", targetNamespace = "http://services.pos.com/", className = "com.pos.services.ExcluirReservaResponse")
    @Action(input = "http://services.pos.com/ManterReservaService/excluirReservaRequest", output = "http://services.pos.com/ManterReservaService/excluirReservaResponse")
    public void excluirReserva(
        @WebParam(name = "arg0", targetNamespace = "")
        Reserva arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "atualizarReserva", targetNamespace = "http://services.pos.com/", className = "com.pos.services.AtualizarReserva")
    @ResponseWrapper(localName = "atualizarReservaResponse", targetNamespace = "http://services.pos.com/", className = "com.pos.services.AtualizarReservaResponse")
    @Action(input = "http://services.pos.com/ManterReservaService/atualizarReservaRequest", output = "http://services.pos.com/ManterReservaService/atualizarReservaResponse")
    public void atualizarReserva(
        @WebParam(name = "arg0", targetNamespace = "")
        Reserva arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "cadastrarReserva", targetNamespace = "http://services.pos.com/", className = "com.pos.services.CadastrarReserva")
    @ResponseWrapper(localName = "cadastrarReservaResponse", targetNamespace = "http://services.pos.com/", className = "com.pos.services.CadastrarReservaResponse")
    @Action(input = "http://services.pos.com/ManterReservaService/cadastrarReservaRequest", output = "http://services.pos.com/ManterReservaService/cadastrarReservaResponse")
    public void cadastrarReserva(
        @WebParam(name = "arg0", targetNamespace = "")
        Reserva arg0);

}
