
package com.pos.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ManterPessoaService", targetNamespace = "http://services.pos.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ManterPessoaService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "cadastrarPessoa", targetNamespace = "http://services.pos.com/", className = "com.pos.services.CadastrarPessoa")
    @ResponseWrapper(localName = "cadastrarPessoaResponse", targetNamespace = "http://services.pos.com/", className = "com.pos.services.CadastrarPessoaResponse")
    @Action(input = "http://services.pos.com/ManterPessoaService/cadastrarPessoaRequest", output = "http://services.pos.com/ManterPessoaService/cadastrarPessoaResponse")
    public void cadastrarPessoa(
        @WebParam(name = "arg0", targetNamespace = "")
        Pessoa arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "onConstruct", targetNamespace = "http://services.pos.com/", className = "com.pos.services.OnConstruct")
    @ResponseWrapper(localName = "onConstructResponse", targetNamespace = "http://services.pos.com/", className = "com.pos.services.OnConstructResponse")
    @Action(input = "http://services.pos.com/ManterPessoaService/onConstructRequest", output = "http://services.pos.com/ManterPessoaService/onConstructResponse")
    public void onConstruct();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "onDestroy", targetNamespace = "http://services.pos.com/", className = "com.pos.services.OnDestroy")
    @ResponseWrapper(localName = "onDestroyResponse", targetNamespace = "http://services.pos.com/", className = "com.pos.services.OnDestroyResponse")
    @Action(input = "http://services.pos.com/ManterPessoaService/onDestroyRequest", output = "http://services.pos.com/ManterPessoaService/onDestroyResponse")
    public void onDestroy();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "excluirPessoa", targetNamespace = "http://services.pos.com/", className = "com.pos.services.ExcluirReserva")
    @ResponseWrapper(localName = "excluirPessoaResponse", targetNamespace = "http://services.pos.com/", className = "com.pos.services.ExcluirReservaResponse")
    @Action(input = "http://services.pos.com/ManterPessoaService/excluirPessoaRequest", output = "http://services.pos.com/ManterPessoaService/excluirPessoaResponse")
    public void excluirPessoa(
        @WebParam(name = "arg0", targetNamespace = "")
        Reserva arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "atualizarPessoa", targetNamespace = "http://services.pos.com/", className = "com.pos.services.AtualizarReserva")
    @ResponseWrapper(localName = "atualizarPessoaResponse", targetNamespace = "http://services.pos.com/", className = "com.pos.services.AtualizarReservaResponse")
    @Action(input = "http://services.pos.com/ManterPessoaService/atualizarPessoaRequest", output = "http://services.pos.com/ManterPessoaService/atualizarPessoaResponse")
    public void atualizarPessoa(
        @WebParam(name = "arg0", targetNamespace = "")
        Reserva arg0);

}
