
package com.pos.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ManterLocadoraService", targetNamespace = "http://services.pos.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ManterLocadoraService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "cadastrarLocadora", targetNamespace = "http://services.pos.com/", className = "com.pos.services.CadastrarLocadora")
    @ResponseWrapper(localName = "cadastrarLocadoraResponse", targetNamespace = "http://services.pos.com/", className = "com.pos.services.CadastrarLocadoraResponse")
    @Action(input = "http://services.pos.com/ManterLocadoraService/cadastrarLocadoraRequest", output = "http://services.pos.com/ManterLocadoraService/cadastrarLocadoraResponse")
    public void cadastrarLocadora(
        @WebParam(name = "arg0", targetNamespace = "")
        Locadora arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "onConstruct", targetNamespace = "http://services.pos.com/", className = "com.pos.services.OnConstruct")
    @ResponseWrapper(localName = "onConstructResponse", targetNamespace = "http://services.pos.com/", className = "com.pos.services.OnConstructResponse")
    @Action(input = "http://services.pos.com/ManterLocadoraService/onConstructRequest", output = "http://services.pos.com/ManterLocadoraService/onConstructResponse")
    public void onConstruct();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "onDestroy", targetNamespace = "http://services.pos.com/", className = "com.pos.services.OnDestroy")
    @ResponseWrapper(localName = "onDestroyResponse", targetNamespace = "http://services.pos.com/", className = "com.pos.services.OnDestroyResponse")
    @Action(input = "http://services.pos.com/ManterLocadoraService/onDestroyRequest", output = "http://services.pos.com/ManterLocadoraService/onDestroyResponse")
    public void onDestroy();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "excluirLocadora", targetNamespace = "http://services.pos.com/", className = "com.pos.services.ExcluirReserva")
    @ResponseWrapper(localName = "excluirLocadoraResponse", targetNamespace = "http://services.pos.com/", className = "com.pos.services.ExcluirReservaResponse")
    @Action(input = "http://services.pos.com/ManterLocadoraService/excluirLocadoraRequest", output = "http://services.pos.com/ManterLocadoraService/excluirLocadoraResponse")
    public void excluirLocadora(
        @WebParam(name = "arg0", targetNamespace = "")
        Reserva arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "atualizaLocadora", targetNamespace = "http://services.pos.com/", className = "com.pos.services.AtualizarReserva")
    @ResponseWrapper(localName = "atualizaLocadoraResponse", targetNamespace = "http://services.pos.com/", className = "com.pos.services.AtualizarReservaResponse")
    @Action(input = "http://services.pos.com/ManterLocadoraService/atualizaLocadoraRequest", output = "http://services.pos.com/ManterLocadoraService/atualizaLocadoraResponse")
    public void atualizaLocadora(
        @WebParam(name = "arg0", targetNamespace = "")
        Reserva arg0);

}
