
package com.pos.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ManterEnderecoService", targetNamespace = "http://services.pos.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ManterEnderecoService {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "onConstruct", targetNamespace = "http://services.pos.com/", className = "com.pos.services.OnConstruct")
    @ResponseWrapper(localName = "onConstructResponse", targetNamespace = "http://services.pos.com/", className = "com.pos.services.OnConstructResponse")
    @Action(input = "http://services.pos.com/ManterEnderecoService/onConstructRequest", output = "http://services.pos.com/ManterEnderecoService/onConstructResponse")
    public void onConstruct();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "onDestroy", targetNamespace = "http://services.pos.com/", className = "com.pos.services.OnDestroy")
    @ResponseWrapper(localName = "onDestroyResponse", targetNamespace = "http://services.pos.com/", className = "com.pos.services.OnDestroyResponse")
    @Action(input = "http://services.pos.com/ManterEnderecoService/onDestroyRequest", output = "http://services.pos.com/ManterEnderecoService/onDestroyResponse")
    public void onDestroy();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "atualizarEndereco", targetNamespace = "http://services.pos.com/", className = "com.pos.services.AtualizarEndereco")
    @ResponseWrapper(localName = "atualizarEnderecoResponse", targetNamespace = "http://services.pos.com/", className = "com.pos.services.AtualizarEnderecoResponse")
    @Action(input = "http://services.pos.com/ManterEnderecoService/atualizarEnderecoRequest", output = "http://services.pos.com/ManterEnderecoService/atualizarEnderecoResponse")
    public void atualizarEndereco(
        @WebParam(name = "arg0", targetNamespace = "")
        Endereco arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "excluirEndereco", targetNamespace = "http://services.pos.com/", className = "com.pos.services.ExcluirEndereco")
    @ResponseWrapper(localName = "excluirEnderecoResponse", targetNamespace = "http://services.pos.com/", className = "com.pos.services.ExcluirEnderecoResponse")
    @Action(input = "http://services.pos.com/ManterEnderecoService/excluirEnderecoRequest", output = "http://services.pos.com/ManterEnderecoService/excluirEnderecoResponse")
    public void excluirEndereco(
        @WebParam(name = "arg0", targetNamespace = "")
        Endereco arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "cadastrarEndereco", targetNamespace = "http://services.pos.com/", className = "com.pos.services.CadastrarEndereco")
    @ResponseWrapper(localName = "cadastrarEnderecoResponse", targetNamespace = "http://services.pos.com/", className = "com.pos.services.CadastrarEnderecoResponse")
    @Action(input = "http://services.pos.com/ManterEnderecoService/cadastrarEnderecoRequest", output = "http://services.pos.com/ManterEnderecoService/cadastrarEnderecoResponse")
    public void cadastrarEndereco(
        @WebParam(name = "arg0", targetNamespace = "")
        Endereco arg0);

}
