
package com.pos.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ManterCarroService", targetNamespace = "http://services.pos.com/", wsdlLocation = "http://localhost:8080/LocaCar-App/ManterCarroService?WSDL")
public class ManterCarroService_Service
    extends Service
{

    private final static URL MANTERCARROSERVICE_WSDL_LOCATION;
    private final static WebServiceException MANTERCARROSERVICE_EXCEPTION;
    private final static QName MANTERCARROSERVICE_QNAME = new QName("http://services.pos.com/", "ManterCarroService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/LocaCar-App/ManterCarroService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MANTERCARROSERVICE_WSDL_LOCATION = url;
        MANTERCARROSERVICE_EXCEPTION = e;
    }

    public ManterCarroService_Service() {
        super(__getWsdlLocation(), MANTERCARROSERVICE_QNAME);
    }

    public ManterCarroService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MANTERCARROSERVICE_QNAME, features);
    }

    public ManterCarroService_Service(URL wsdlLocation) {
        super(wsdlLocation, MANTERCARROSERVICE_QNAME);
    }

    public ManterCarroService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MANTERCARROSERVICE_QNAME, features);
    }

    public ManterCarroService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ManterCarroService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ManterCarroService
     */
    @WebEndpoint(name = "ManterCarroServicePort")
    public ManterCarroService getManterCarroServicePort() {
        return super.getPort(new QName("http://services.pos.com/", "ManterCarroServicePort"), ManterCarroService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ManterCarroService
     */
    @WebEndpoint(name = "ManterCarroServicePort")
    public ManterCarroService getManterCarroServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.pos.com/", "ManterCarroServicePort"), ManterCarroService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MANTERCARROSERVICE_EXCEPTION!= null) {
            throw MANTERCARROSERVICE_EXCEPTION;
        }
        return MANTERCARROSERVICE_WSDL_LOCATION;
    }

}
