
package com.pos.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ManterReservaService", targetNamespace = "http://services.pos.com/", wsdlLocation = "http://localhost:8080/LocaCar-App/ManterReservaService?WSDL")
public class ManterReservaService_Service
    extends Service
{

    private final static URL MANTERRESERVASERVICE_WSDL_LOCATION;
    private final static WebServiceException MANTERRESERVASERVICE_EXCEPTION;
    private final static QName MANTERRESERVASERVICE_QNAME = new QName("http://services.pos.com/", "ManterReservaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/LocaCar-App/ManterReservaService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MANTERRESERVASERVICE_WSDL_LOCATION = url;
        MANTERRESERVASERVICE_EXCEPTION = e;
    }

    public ManterReservaService_Service() {
        super(__getWsdlLocation(), MANTERRESERVASERVICE_QNAME);
    }

    public ManterReservaService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MANTERRESERVASERVICE_QNAME, features);
    }

    public ManterReservaService_Service(URL wsdlLocation) {
        super(wsdlLocation, MANTERRESERVASERVICE_QNAME);
    }

    public ManterReservaService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MANTERRESERVASERVICE_QNAME, features);
    }

    public ManterReservaService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ManterReservaService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ManterReservaService
     */
    @WebEndpoint(name = "ManterReservaServicePort")
    public ManterReservaService getManterReservaServicePort() {
        return super.getPort(new QName("http://services.pos.com/", "ManterReservaServicePort"), ManterReservaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ManterReservaService
     */
    @WebEndpoint(name = "ManterReservaServicePort")
    public ManterReservaService getManterReservaServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.pos.com/", "ManterReservaServicePort"), ManterReservaService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MANTERRESERVASERVICE_EXCEPTION!= null) {
            throw MANTERRESERVASERVICE_EXCEPTION;
        }
        return MANTERRESERVASERVICE_WSDL_LOCATION;
    }

}
